<a href="https://colab.research.google.com/github/Betul02/orneklem-korelasyon-matrisi/blob/main/03_12_2023_ist3001'in_PDF'%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import numpy as np

In [86]:
#matrisi oluşturma ve yazdırma
x1 = np.array([7, 9, 8])
x2 = np.array([8, 5, 2])
x3 = np.array([2, 2, 10])
x4 = np.array([10, 1, 1])
x5 = np.array([5, 1, 2])
x6 = np.array([2, 6, 4])
x7 = np.array([5, 8, 2])
x8 = np.array([2, 8, 2])
x9 = np.array([1, 2, 9])
x10 = np.array([6, 7, 9])
x = np.array([x1, x2, x3, x4, x5, x6, x7, x8, x9, x10]).T;
print("veri matrisi = x")
print(x)

veri matrisi = x
[[ 7  8  2 10  5  2  5  2  1  6]
 [ 9  5  2  1  1  6  8  8  2  7]
 [ 8  2 10  1  2  4  2  2  9  9]]


In [87]:
#boyutunu öğrenme
x.shape

(3, 10)

In [88]:
#örneklem ortalama vektörü
örneklem_ort = np.array([np.mean(x, axis=1)]).T
print("örneklem ortalama vektörü")
print(örneklem_ort)

örneklem ortalama vektörü
[[4.8]
 [4.9]
 [4.9]]


In [89]:
#örneklem varyans-kovaryans matrisi
def örneklem_var_cov_matrisi(x, örneklem_ort):

    degisken_sayisi = x.shape[0]
    gozlem_sayisi = x.shape[1]

    # Örneklem varyans-kovaryans matrisini hesaplama
    # Elemanları 0 olan boş matris oluşturma
    kovaryans_matrisi = np.zeros((degisken_sayisi, degisken_sayisi))

    for i in range(degisken_sayisi):
        for j in range(degisken_sayisi):
            S_i = x[i, :] - örneklem_ort[i]
            S_j = x[j, :] - örneklem_ort[j]
            kovaryans_matrisi[i, j] = np.sum(S_i * S_j) / gozlem_sayisi

    return kovaryans_matrisi



# Fonksiyonu çağırma
kovaryans_matrisi = örneklem_var_cov_matrisi(x, örneklem_ort)

# Sonuçları yazdırma
print("Örneklem Varyans-Kovaryans Matrisi:")
print(kovaryans_matrisi)

Örneklem Varyans-Kovaryans Matrisi:
[[ 8.16 -0.12 -3.82]
 [-0.12  8.89  0.19]
 [-3.82  0.19 11.89]]


In [94]:
def hesaplanan_korelasyon_matrisi(x):

    # Örneklem korelasyon matrisini hesaplama
    korelasyon_matrisi = np.zeros((degisken_sayisi, degisken_sayisi))

    for i in range(degisken_sayisi):
        for j in range(degisken_sayisi):
            # Her iki değişkenin örneklem ortalamasını hesapla
            örneklem_ort_i = np.mean(x[i, :])
            örneklem_ort_j = np.mean(x[j, :])

            # İki değişken arasındaki örneklem korelasyonunu hesapla
            kovaryans = np.sum((x[i, :] - örneklem_ort_i) * (x[j, :] - örneklem_ort_j))
            standart_sapma = np.sqrt(np.sum((x[i, :] - örneklem_ort_i)**2) * np.sum((x[j, :] - örneklem_ort_j)**2))

            # Korelasyon matrisine değeri atla
            korelasyon_matrisi[i, j] = kovaryans / standart_sapma

    return korelasyon_matrisi


# Fonksiyonu çağırma
korelasyon_matrisi = hesaplanan_korelasyon_matrisi(x)

# Sonuçları yazdırma
print("Örneklem Korelasyon Matrisi:")
print(korelasyon_matrisi)

Örneklem Korelasyon Matrisi:
[[ 1.         -0.01408917 -0.38781746]
 [-0.01408917  1.          0.01848042]
 [-0.38781746  0.01848042  1.        ]]
